### ISSUE TITLE
Switch to github pages

### ISSUE THREAD

**Issue by saiichihashimoto** [cameronrohani/hovercardslanding#4]
It's annoying because we're doing browserify and postcss, so its not just a static webpage, currently.

- [ ] Delete the AWS buckets when closing

**Comment by saiichihashimoto** [comment]
I want to do this in a way that we can still browserify/postcss/preprocess everything. [This guide](https://gist.github.com/cobyism/4730490) is exactly how we're going to accomplish that. We can throw in a [`pre-push`](https://www.npmjs.com/package/pre-push) hook and then we can just have it happen on push. Golden.

I'm going to try this on kogg/kogg.github.io first Because why not.

**Comment by cameronrohani** [comment]
The DNS settings are taking some time, but www.hovercards.com now redirects to hovercards.com AND hovercards.com sometimes uses the version from github pages. You can tell since the `privacy.html` in `gh-pages` has google analytics and the AWS one doesn't. Going to close when this is stable.

**Comment by saiichihashimoto** [comment]
The DNS settings are taking some time, but www.hovercards.com now redirects to hovercards.com AND hovercards.com sometimes uses the version from github pages. You can tell since the `privacy.html` in `gh-pages` has google analytics and the AWS one doesn't. Going to close when this is stable.

**Comment by saiichihashimoto** [comment]
Just to remind myself:

- [ ] Delete the AWS buckets when you close this.
